### ISSUE TITLE
[RESTWS] Avoid exception while importing YAML because SecurityScheme.getScheme() is null

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#449]
```
...
 securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
    bearer_auth:
      type: http
      name: Authorization
      scheme: bearer
      bearerFormat: JWT
      in: header
```
